[profile.default]
src = "src"
script = "script"
out = "out"
solc = "0.8.23"
libs = ["lib", "@openzeppelin/=lib/openzeppelin-contracts"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }