[profile.default]
src = "src"
script = "script"
out = "out"
libs = ["lib", "@openzeppelin/=lib/openzeppelin-contracts"]
viaIR = true
auto_detect_solc = true
optimizer = true
optimizer-runs = 10_000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }